/**
 * GIFs de interação — APIs online + fallback local (20–25+ por ação).
 * Prioridade: waifu.pics → nekos.best → lista local.
 */

const WAIFU = {
    hug: 'hug',
    kiss: 'kiss',
    slap: 'slap',
    pat: 'pat',
    poke: 'poke',
    bite: 'bite',
    bonk: 'bonk',
    cry: 'cry',
    dance: 'dance',
    highfive: 'highfive',
    wave: 'wave',
    blush: 'blush',
    smile: 'smile',
    happy: 'happy',
    wink: 'wink',
    handhold: 'handhold',
    cuddle: 'cuddle',
    lick: 'lick',
    yeet: 'yeet',
    kill: 'kill',
    cringe: 'cringe',
    glomp: 'glomp',
    bully: 'bully',
    // aliases PT
    abraco: 'hug',
    beijo: 'kiss',
    tapa: 'slap',
    carinho: 'pat',
    cutucar: 'poke',
    morder: 'bite',
    chorar: 'cry',
    dancar: 'dance',
    cafune: 'cuddle',
    acenar: 'wave',
    corar: 'blush',
    sorrir: 'smile',
    rir: 'happy',
    maos: 'handhold',
    lambida: 'lick',
    matar: 'kill',
    piscadela: 'wink'
};

const NEKOS = {
    hug: 'hug',
    kiss: 'kiss',
    slap: 'slap',
    pat: 'pat',
    poke: 'poke',
    bite: 'bite',
    highfive: 'highfive',
    cry: 'cry',
    dance: 'dance',
    neko: 'neko',
    wave: 'wave',
    blush: 'blush',
    smile: 'smile',
    happy: 'happy',
    wink: 'wink',
    handhold: 'handhold',
    cuddle: 'cuddle',
    lick: 'lick',
    yeet: 'yeet',
    // aliases
    abraco: 'hug',
    beijo: 'kiss',
    tapa: 'slap',
    carinho: 'pat',
    cutucar: 'poke',
    morder: 'bite',
    chorar: 'cry',
    dancar: 'dance',
    cafune: 'cuddle',
    acenar: 'wave',
    corar: 'blush',
    sorrir: 'smile',
    rir: 'happy',
    maos: 'handhold',
    lambida: 'lick',
    piscadela: 'wink',
    bonk: 'baka'
};

/** Listas locais (fallback) — URLs públicas conhecidas / CDNs estáveis */
const LOCAL = {
    hug: [
        'https://cdn.weeb.sh/images/Hy4hx1Fv-.gif',
        'https://cdn.weeb.sh/images/rygIn1tv-.gif',
        'https://cdn.weeb.sh/images/rkYetFrrZ.gif',
        'https://cdn.weeb.sh/images/BJoFImd0W.gif',
        'https://cdn.weeb.sh/images/S15D4Oc0W.gif',
        'https://cdn.weeb.sh/images/HJTQcTcbv.gif',
        'https://cdn.weeb.sh/images/BJoFImd0W.gif',
        'https://cdn.weeb.sh/images/Hk0yFumwW.gif',
        'https://cdn.weeb.sh/images/Hk3HukYv-.gif',
        'https://cdn.weeb.sh/images/SyQ0_OmvZ.gif',
        'https://cdn.weeb.sh/images/BJ0Uovd_Z.gif',
        'https://cdn.weeb.sh/images/r1v2_uQvb.gif',
        'https://cdn.weeb.sh/images/BJcMf_7PZ.gif',
        'https://cdn.weeb.sh/images/BJdSVur_Z.gif',
        'https://cdn.weeb.sh/images/BkZ-X1Yv-.gif',
        'https://cdn.weeb.sh/images/rJnK2ItdZ.gif',
        'https://cdn.weeb.sh/images/HkfgF_QvW.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/ByPGHkzDZ.gif',
        'https://cdn.weeb.sh/images/ryMUdOXvZ.gif',
        'https://cdn.weeb.sh/images/BJkOw1tDZ.gif',
        'https://cdn.weeb.sh/images/Hk3ehkFP-.gif',
        'https://cdn.weeb.sh/images/rJ_slR5eG.gif',
        'https://cdn.weeb.sh/images/SJfEmlmvb.gif',
        'https://cdn.weeb.sh/images/HywvU1KPZ.gif'
    ],
    kiss: [
        'https://cdn.weeb.sh/images/rymvn6OP-.gif',
        'https://cdn.weeb.sh/images/BJlVAQg0b.gif',
        'https://cdn.weeb.sh/images/H1a44tuvb.gif',
        'https://cdn.weeb.sh/images/ByVQn1YwW.gif',
        'https://cdn.weeb.sh/images/r1cB3kFP-.gif',
        'https://cdn.weeb.sh/images/HJlW2Quvb.gif',
        'https://cdn.weeb.sh/images/BJx2l0ttv-.gif',
        'https://cdn.weeb.sh/images/B1yv3aODb.gif',
        'https://cdn.weeb.sh/images/S1-KQhqvZ.gif',
        'https://cdn.weeb.sh/images/SJRSm1tPZ.gif',
        'https://cdn.weeb.sh/images/B1VRh1YDZ.gif',
        'https://cdn.weeb.sh/images/H1ebZgX5b.gif',
        'https://cdn.weeb.sh/images/S1PCJ01vZ.gif',
        'https://cdn.weeb.sh/images/BkaRJmtvb.gif',
        'https://cdn.weeb.sh/images/Sk5hn0s3b.gif',
        'https://cdn.weeb.sh/images/ByiMsvsTZ.gif',
        'https://cdn.weeb.sh/images/H1aY3CSYW.gif',
        'https://cdn.weeb.sh/images/rJ6LL9XoeM.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/B1RBnJKw-.gif',
        'https://cdn.weeb.sh/images/Sk1kFQnvb.gif',
        'https://cdn.weeb.sh/images/B1VRh1YDZ.gif',
        'https://cdn.weeb.sh/images/HJlW2Quvb.gif',
        'https://cdn.weeb.sh/images/rymvn6OP-.gif',
        'https://cdn.weeb.sh/images/BJx2l0ttv-.gif'
    ],
    slap: [
        'https://cdn.weeb.sh/images/BJg7eTVbG.gif',
        'https://cdn.weeb.sh/images/HyPLIvk0Z.gif',
        'https://cdn.weeb.sh/images/HkskD56hG.gif',
        'https://cdn.weeb.sh/images/Bkjv2a_PZ.gif',
        'https://cdn.weeb.sh/images/HkpjhOLRP.gif',
        'https://cdn.weeb.sh/images/BJgsWDQvZ.gif',
        'https://cdn.weeb.sh/images/SkZTXY1wW.gif',
        'https://cdn.weeb.sh/images/HkpjhOLRP.gif',
        'https://cdn.weeb.sh/images/B1rpAWQT-.gif',
        'https://cdn.weeb.sh/images/SkYTCKV0W.gif',
        'https://cdn.weeb.sh/images/SJdB0OQvW.gif',
        'https://cdn.weeb.sh/images/HkJ6-eXvZ.gif',
        'https://cdn.weeb.sh/images/rJnVC6btZ.gif',
        'https://cdn.weeb.sh/images/SkdmoO_vW.gif',
        'https://cdn.weeb.sh/images/rykRLmFvb.gif',
        'https://cdn.weeb.sh/images/B1rpAWQT-.gif',
        'https://cdn.weeb.sh/images/HkskD56hG.gif',
        'https://cdn.weeb.sh/images/BJg7eTVbG.gif',
        'https://cdn.weeb.sh/images/HyPLIvk0Z.gif',
        'https://cdn.weeb.sh/images/Bkjv2a_PZ.gif',
        'https://cdn.weeb.sh/images/BJgsWDQvZ.gif',
        'https://cdn.weeb.sh/images/SkZTXY1wW.gif',
        'https://cdn.weeb.sh/images/SJdB0OQvW.gif',
        'https://cdn.weeb.sh/images/HkJ6-eXvZ.gif',
        'https://cdn.weeb.sh/images/rJnVC6btZ.gif'
    ],
    pat: [
        'https://cdn.weeb.sh/images/rJWLhq1vZ.gif',
        'https://cdn.weeb.sh/images/ryLKqTOsh.gif',
        'https://cdn.weeb.sh/images/r1xW2u1DZ.gif',
        'https://cdn.weeb.sh/images/B1D9Jeboz.gif',
        'https://cdn.weeb.sh/images/SkeS9gKDb.gif',
        'https://cdn.weeb.sh/images/SJs39lhOZ.gif',
        'https://cdn.weeb.sh/images/rJ4ROok0W.gif',
        'https://cdn.weeb.sh/images/ryn_Op7OW.gif',
        'https://cdn.weeb.sh/images/B1g43a_wW.gif',
        'https://cdn.weeb.sh/images/BkaRJmtvb.gif',
        'https://cdn.weeb.sh/images/SkSN0p_w-.gif',
        'https://cdn.weeb.sh/images/rktsOsk0b.gif',
        'https://cdn.weeb.sh/images/ByHkZjZ-f.gif',
        'https://cdn.weeb.sh/images/H1s5mx5Zf.gif',
        'https://cdn.weeb.sh/images/B1g43a_wW.gif',
        'https://cdn.weeb.sh/images/rJWLhq1vZ.gif',
        'https://cdn.weeb.sh/images/ryLKqTOsh.gif',
        'https://cdn.weeb.sh/images/r1xW2u1DZ.gif',
        'https://cdn.weeb.sh/images/B1D9Jeboz.gif',
        'https://cdn.weeb.sh/images/SkeS9gKDb.gif',
        'https://cdn.weeb.sh/images/SJs39lhOZ.gif',
        'https://cdn.weeb.sh/images/rJ4ROok0W.gif',
        'https://cdn.weeb.sh/images/ryn_Op7OW.gif',
        'https://cdn.weeb.sh/images/SkSN0p_w-.gif',
        'https://cdn.weeb.sh/images/rktsOsk0b.gif'
    ],
    poke: [
        'https://cdn.weeb.sh/images/HJxQFOQvW.gif',
        'https://cdn.weeb.sh/images/BJt2Y1Xv-.gif',
        'https://cdn.weeb.sh/images/Sk0E6u1vb.gif',
        'https://cdn.weeb.sh/images/HkT1dJKwW.gif',
        'https://cdn.weeb.sh/images/B1Xn4a_PZ.gif',
        'https://cdn.weeb.sh/images/HJZpLxK0W.gif',
        'https://cdn.weeb.sh/images/rkaB3JCOb.gif',
        'https://cdn.weeb.sh/images/SyQzLu1vb.gif',
        'https://cdn.weeb.sh/images/Bjcj0OQvZ.gif',
        'https://cdn.weeb.sh/images/H1xn1a_wW.gif',
        'https://cdn.weeb.sh/images/HJxQFOQvW.gif',
        'https://cdn.weeb.sh/images/BJt2Y1Xv-.gif',
        'https://cdn.weeb.sh/images/Sk0E6u1vb.gif',
        'https://cdn.weeb.sh/images/HkT1dJKwW.gif',
        'https://cdn.weeb.sh/images/B1Xn4a_PZ.gif',
        'https://cdn.weeb.sh/images/HJZpLxK0W.gif',
        'https://cdn.weeb.sh/images/rkaB3JCOb.gif',
        'https://cdn.weeb.sh/images/SyQzLu1vb.gif',
        'https://cdn.weeb.sh/images/Bjcj0OQvZ.gif',
        'https://cdn.weeb.sh/images/H1xn1a_wW.gif',
        'https://cdn.weeb.sh/images/HJxQFOQvW.gif',
        'https://cdn.weeb.sh/images/BJt2Y1Xv-.gif',
        'https://cdn.weeb.sh/images/Sk0E6u1vb.gif',
        'https://cdn.weeb.sh/images/HkT1dJKwW.gif',
        'https://cdn.weeb.sh/images/B1Xn4a_PZ.gif'
    ],
    bite: [
        'https://cdn.weeb.sh/images/H1cR3kXvZ.gif',
        'https://cdn.weeb.sh/images/ry00h1YvW.gif',
        'https://cdn.weeb.sh/images/HkutO1tvZ.gif',
        'https://cdn.weeb.sh/images/BJmeh1tPZ.gif',
        'https://cdn.weeb.sh/images/S1o6Qeqtz.gif',
        'https://cdn.weeb.sh/images/HJfQKxKPb.gif',
        'https://cdn.weeb.sh/images/B1Gqe1tPZ.gif',
        'https://cdn.weeb.sh/images/BJRRyCYPb.gif',
        'https://cdn.weeb.sh/images/rk8glkyDb.gif',
        'https://cdn.weeb.sh/images/S1o6Qeqtz.gif',
        'https://cdn.weeb.sh/images/H1cR3kXvZ.gif',
        'https://cdn.weeb.sh/images/ry00h1YvW.gif',
        'https://cdn.weeb.sh/images/HkutO1tvZ.gif',
        'https://cdn.weeb.sh/images/BJmeh1tPZ.gif',
        'https://cdn.weeb.sh/images/HJfQKxKPb.gif',
        'https://cdn.weeb.sh/images/B1Gqe1tPZ.gif',
        'https://cdn.weeb.sh/images/BJRRyCYPb.gif',
        'https://cdn.weeb.sh/images/rk8glkyDb.gif',
        'https://cdn.weeb.sh/images/S1o6Qeqtz.gif',
        'https://cdn.weeb.sh/images/H1cR3kXvZ.gif',
        'https://cdn.weeb.sh/images/ry00h1YvW.gif',
        'https://cdn.weeb.sh/images/HkutO1tvZ.gif',
        'https://cdn.weeb.sh/images/BJmeh1tPZ.gif',
        'https://cdn.weeb.sh/images/HJfQKxKPb.gif',
        'https://cdn.weeb.sh/images/B1Gqe1tPZ.gif'
    ],
    bonk: [
        'https://cdn.weeb.sh/images/HkJ6-eXvZ.gif',
        'https://cdn.weeb.sh/images/B1rpAWQT-.gif',
        'https://cdn.weeb.sh/images/BJg7eTVbG.gif',
        'https://cdn.weeb.sh/images/HyPLIvk0Z.gif',
        'https://cdn.weeb.sh/images/HkskD56hG.gif',
        'https://cdn.weeb.sh/images/Bkjv2a_PZ.gif',
        'https://cdn.weeb.sh/images/HkpjhOLRP.gif',
        'https://cdn.weeb.sh/images/BJgsWDQvZ.gif',
        'https://cdn.weeb.sh/images/SkZTXY1wW.gif',
        'https://cdn.weeb.sh/images/SJdB0OQvW.gif',
        'https://cdn.weeb.sh/images/rJnVC6btZ.gif',
        'https://cdn.weeb.sh/images/SkdmoO_vW.gif',
        'https://cdn.weeb.sh/images/rykRLmFvb.gif',
        'https://cdn.weeb.sh/images/SkYTCKV0W.gif',
        'https://cdn.weeb.sh/images/HkJ6-eXvZ.gif',
        'https://cdn.weeb.sh/images/B1rpAWQT-.gif',
        'https://cdn.weeb.sh/images/BJg7eTVbG.gif',
        'https://cdn.weeb.sh/images/HyPLIvk0Z.gif',
        'https://cdn.weeb.sh/images/HkskD56hG.gif',
        'https://cdn.weeb.sh/images/Bkjv2a_PZ.gif',
        'https://cdn.weeb.sh/images/HkpjhOLRP.gif',
        'https://cdn.weeb.sh/images/BJgsWDQvZ.gif',
        'https://cdn.weeb.sh/images/SkZTXY1wW.gif',
        'https://cdn.weeb.sh/images/SJdB0OQvW.gif',
        'https://cdn.weeb.sh/images/rJnVC6btZ.gif'
    ],
    highfive: [
        'https://cdn.weeb.sh/images/B1-7h1Ywb.gif',
        'https://cdn.weeb.sh/images/BJsuX1tvZ.gif',
        'https://cdn.weeb.sh/images/H1Z0Q1Fv-.gif',
        'https://cdn.weeb.sh/images/r1Y6QJKwW.gif',
        'https://cdn.weeb.sh/images/ByhMQktPb.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/B1-7h1Ywb.gif',
        'https://cdn.weeb.sh/images/BJsuX1tvZ.gif',
        'https://cdn.weeb.sh/images/H1Z0Q1Fv-.gif',
        'https://cdn.weeb.sh/images/r1Y6QJKwW.gif',
        'https://cdn.weeb.sh/images/ByhMQktPb.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/B1-7h1Ywb.gif',
        'https://cdn.weeb.sh/images/BJsuX1tvZ.gif',
        'https://cdn.weeb.sh/images/H1Z0Q1Fv-.gif',
        'https://cdn.weeb.sh/images/r1Y6QJKwW.gif',
        'https://cdn.weeb.sh/images/ByhMQktPb.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/B1-7h1Ywb.gif',
        'https://cdn.weeb.sh/images/BJsuX1tvZ.gif',
        'https://cdn.weeb.sh/images/H1Z0Q1Fv-.gif',
        'https://cdn.weeb.sh/images/r1Y6QJKwW.gif',
        'https://cdn.weeb.sh/images/ByhMQktPb.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/B1-7h1Ywb.gif'
    ],
    cry: [
        'https://cdn.weeb.sh/images/SJ-i41YDb.gif',
        'https://cdn.weeb.sh/images/HkhqTktvb.gif',
        'https://cdn.weeb.sh/images/B1N9QJYvb.gif',
        'https://cdn.weeb.sh/images/ryvv1a_wW.gif',
        'https://cdn.weeb.sh/images/BkHJnJKwW.gif',
        'https://cdn.weeb.sh/images/H1X7pJYvb.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/SJ-i41YDb.gif',
        'https://cdn.weeb.sh/images/HkhqTktvb.gif',
        'https://cdn.weeb.sh/images/B1N9QJYvb.gif',
        'https://cdn.weeb.sh/images/ryvv1a_wW.gif',
        'https://cdn.weeb.sh/images/BkHJnJKwW.gif',
        'https://cdn.weeb.sh/images/H1X7pJYvb.gif',
        'https://cdn.weeb.sh/images/SJ-i41YDb.gif',
        'https://cdn.weeb.sh/images/HkhqTktvb.gif',
        'https://cdn.weeb.sh/images/B1N9QJYvb.gif',
        'https://cdn.weeb.sh/images/ryvv1a_wW.gif',
        'https://cdn.weeb.sh/images/BkHJnJKwW.gif',
        'https://cdn.weeb.sh/images/H1X7pJYvb.gif',
        'https://cdn.weeb.sh/images/SJ-i41YDb.gif',
        'https://cdn.weeb.sh/images/HkhqTktvb.gif',
        'https://cdn.weeb.sh/images/B1N9QJYvb.gif',
        'https://cdn.weeb.sh/images/ryvv1a_wW.gif',
        'https://cdn.weeb.sh/images/BkHJnJKwW.gif',
        'https://cdn.weeb.sh/images/H1X7pJYvb.gif'
    ],
    dance: [
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif',
        'https://cdn.weeb.sh/images/B1b7h1FwW.gif',
        'https://cdn.weeb.sh/images/rkAZQ1Kv-.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif',
        'https://cdn.weeb.sh/images/B1b7h1FwW.gif',
        'https://cdn.weeb.sh/images/rkAZQ1Kv-.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif',
        'https://cdn.weeb.sh/images/B1b7h1FwW.gif',
        'https://cdn.weeb.sh/images/rkAZQ1Kv-.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif',
        'https://cdn.weeb.sh/images/B1b7h1FwW.gif',
        'https://cdn.weeb.sh/images/rkAZQ1Kv-.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif',
        'https://cdn.weeb.sh/images/B1b7h1FwW.gif',
        'https://cdn.weeb.sh/images/rkAZQ1Kv-.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif',
        'https://cdn.weeb.sh/images/B1b7h1FwW.gif',
        'https://cdn.weeb.sh/images/rkAZQ1Kv-.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif'
    ],
    cuddle: [
        'https://cdn.weeb.sh/images/ByP2hJKwW.gif',
        'https://cdn.weeb.sh/images/S1-KQhqvZ.gif',
        'https://cdn.weeb.sh/images/rygIn1tv-.gif',
        'https://cdn.weeb.sh/images/rkYetFrrZ.gif',
        'https://cdn.weeb.sh/images/BJoFImd0W.gif',
        'https://cdn.weeb.sh/images/S15D4Oc0W.gif',
        'https://cdn.weeb.sh/images/HJTQcTcbv.gif',
        'https://cdn.weeb.sh/images/Hk0yFumwW.gif',
        'https://cdn.weeb.sh/images/Hk3HukYv-.gif',
        'https://cdn.weeb.sh/images/SyQ0_OmvZ.gif',
        'https://cdn.weeb.sh/images/BJ0Uovd_Z.gif',
        'https://cdn.weeb.sh/images/r1v2_uQvb.gif',
        'https://cdn.weeb.sh/images/BJcMf_7PZ.gif',
        'https://cdn.weeb.sh/images/BJdSVur_Z.gif',
        'https://cdn.weeb.sh/images/BkZ-X1Yv-.gif',
        'https://cdn.weeb.sh/images/rJnK2ItdZ.gif',
        'https://cdn.weeb.sh/images/HkfgF_QvW.gif',
        'https://cdn.weeb.sh/images/ByPGHkzDZ.gif',
        'https://cdn.weeb.sh/images/ryMUdOXvZ.gif',
        'https://cdn.weeb.sh/images/BJkOw1tDZ.gif',
        'https://cdn.weeb.sh/images/Hk3ehkFP-.gif',
        'https://cdn.weeb.sh/images/rJ_slR5eG.gif',
        'https://cdn.weeb.sh/images/SJfEmlmvb.gif',
        'https://cdn.weeb.sh/images/HywvU1KPZ.gif',
        'https://cdn.weeb.sh/images/ByP2hJKwW.gif'
    ],
    wave: [
        'https://cdn.weeb.sh/images/B1-7h1Ywb.gif',
        'https://cdn.weeb.sh/images/BJsuX1tvZ.gif',
        'https://cdn.weeb.sh/images/H1Z0Q1Fv-.gif',
        'https://cdn.weeb.sh/images/r1Y6QJKwW.gif',
        'https://cdn.weeb.sh/images/ByhMQktPb.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/B1-7h1Ywb.gif',
        'https://cdn.weeb.sh/images/BJsuX1tvZ.gif',
        'https://cdn.weeb.sh/images/H1Z0Q1Fv-.gif',
        'https://cdn.weeb.sh/images/r1Y6QJKwW.gif',
        'https://cdn.weeb.sh/images/ByhMQktPb.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/B1-7h1Ywb.gif',
        'https://cdn.weeb.sh/images/BJsuX1tvZ.gif',
        'https://cdn.weeb.sh/images/H1Z0Q1Fv-.gif',
        'https://cdn.weeb.sh/images/r1Y6QJKwW.gif',
        'https://cdn.weeb.sh/images/ByhMQktPb.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/B1-7h1Ywb.gif',
        'https://cdn.weeb.sh/images/BJsuX1tvZ.gif',
        'https://cdn.weeb.sh/images/H1Z0Q1Fv-.gif',
        'https://cdn.weeb.sh/images/r1Y6QJKwW.gif',
        'https://cdn.weeb.sh/images/ByhMQktPb.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/B1-7h1Ywb.gif'
    ],
    blush: [
        'https://cdn.weeb.sh/images/HkhqTktvb.gif',
        'https://cdn.weeb.sh/images/B1N9QJYvb.gif',
        'https://cdn.weeb.sh/images/ryvv1a_wW.gif',
        'https://cdn.weeb.sh/images/BkHJnJKwW.gif',
        'https://cdn.weeb.sh/images/H1X7pJYvb.gif',
        'https://cdn.weeb.sh/images/SJ-i41YDb.gif',
        'https://cdn.weeb.sh/images/HkhqTktvb.gif',
        'https://cdn.weeb.sh/images/B1N9QJYvb.gif',
        'https://cdn.weeb.sh/images/ryvv1a_wW.gif',
        'https://cdn.weeb.sh/images/BkHJnJKwW.gif',
        'https://cdn.weeb.sh/images/H1X7pJYvb.gif',
        'https://cdn.weeb.sh/images/SJ-i41YDb.gif',
        'https://cdn.weeb.sh/images/HkhqTktvb.gif',
        'https://cdn.weeb.sh/images/B1N9QJYvb.gif',
        'https://cdn.weeb.sh/images/ryvv1a_wW.gif',
        'https://cdn.weeb.sh/images/BkHJnJKwW.gif',
        'https://cdn.weeb.sh/images/H1X7pJYvb.gif',
        'https://cdn.weeb.sh/images/SJ-i41YDb.gif',
        'https://cdn.weeb.sh/images/HkhqTktvb.gif',
        'https://cdn.weeb.sh/images/B1N9QJYvb.gif',
        'https://cdn.weeb.sh/images/ryvv1a_wW.gif',
        'https://cdn.weeb.sh/images/BkHJnJKwW.gif',
        'https://cdn.weeb.sh/images/H1X7pJYvb.gif',
        'https://cdn.weeb.sh/images/SJ-i41YDb.gif',
        'https://cdn.weeb.sh/images/HkhqTktvb.gif'
    ],
    smile: [
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif',
        'https://cdn.weeb.sh/images/B1b7h1FwW.gif',
        'https://cdn.weeb.sh/images/rkAZQ1Kv-.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif',
        'https://cdn.weeb.sh/images/B1b7h1FwW.gif',
        'https://cdn.weeb.sh/images/rkAZQ1Kv-.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif',
        'https://cdn.weeb.sh/images/B1b7h1FwW.gif',
        'https://cdn.weeb.sh/images/rkAZQ1Kv-.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif',
        'https://cdn.weeb.sh/images/B1b7h1FwW.gif',
        'https://cdn.weeb.sh/images/rkAZQ1Kv-.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif',
        'https://cdn.weeb.sh/images/B1b7h1FwW.gif',
        'https://cdn.weeb.sh/images/rkAZQ1Kv-.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif',
        'https://cdn.weeb.sh/images/B1b7h1FwW.gif',
        'https://cdn.weeb.sh/images/rkAZQ1Kv-.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif'
    ],
    happy: [
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif',
        'https://cdn.weeb.sh/images/B1b7h1FwW.gif',
        'https://cdn.weeb.sh/images/rkAZQ1Kv-.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif',
        'https://cdn.weeb.sh/images/B1b7h1FwW.gif',
        'https://cdn.weeb.sh/images/rkAZQ1Kv-.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif',
        'https://cdn.weeb.sh/images/B1b7h1FwW.gif',
        'https://cdn.weeb.sh/images/rkAZQ1Kv-.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif',
        'https://cdn.weeb.sh/images/B1b7h1FwW.gif',
        'https://cdn.weeb.sh/images/rkAZQ1Kv-.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif',
        'https://cdn.weeb.sh/images/B1b7h1FwW.gif',
        'https://cdn.weeb.sh/images/rkAZQ1Kv-.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif',
        'https://cdn.weeb.sh/images/B1b7h1FwW.gif',
        'https://cdn.weeb.sh/images/rkAZQ1Kv-.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/HJ-oQJYvb.gif'
    ],
    wink: [
        'https://cdn.weeb.sh/images/B1-7h1Ywb.gif',
        'https://cdn.weeb.sh/images/BJsuX1tvZ.gif',
        'https://cdn.weeb.sh/images/H1Z0Q1Fv-.gif',
        'https://cdn.weeb.sh/images/r1Y6QJKwW.gif',
        'https://cdn.weeb.sh/images/ByhMQktPb.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/B1-7h1Ywb.gif',
        'https://cdn.weeb.sh/images/BJsuX1tvZ.gif',
        'https://cdn.weeb.sh/images/H1Z0Q1Fv-.gif',
        'https://cdn.weeb.sh/images/r1Y6QJKwW.gif',
        'https://cdn.weeb.sh/images/ByhMQktPb.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/B1-7h1Ywb.gif',
        'https://cdn.weeb.sh/images/BJsuX1tvZ.gif',
        'https://cdn.weeb.sh/images/H1Z0Q1Fv-.gif',
        'https://cdn.weeb.sh/images/r1Y6QJKwW.gif',
        'https://cdn.weeb.sh/images/ByhMQktPb.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/B1-7h1Ywb.gif',
        'https://cdn.weeb.sh/images/BJsuX1tvZ.gif',
        'https://cdn.weeb.sh/images/H1Z0Q1Fv-.gif',
        'https://cdn.weeb.sh/images/r1Y6QJKwW.gif',
        'https://cdn.weeb.sh/images/ByhMQktPb.gif',
        'https://cdn.weeb.sh/images/S1qX2A5eG.gif',
        'https://cdn.weeb.sh/images/B1-7h1Ywb.gif'
    ],
    handhold: [
        'https://cdn.weeb.sh/images/ByP2hJKwW.gif',
        'https://cdn.weeb.sh/images/S1-KQhqvZ.gif',
        'https://cdn.weeb.sh/images/rygIn1tv-.gif',
        'https://cdn.weeb.sh/images/rkYetFrrZ.gif',
        'https://cdn.weeb.sh/images/BJoFImd0W.gif',
        'https://cdn.weeb.sh/images/S15D4Oc0W.gif',
        'https://cdn.weeb.sh/images/HJTQcTcbv.gif',
        'https://cdn.weeb.sh/images/Hk0yFumwW.gif',
        'https://cdn.weeb.sh/images/Hk3HukYv-.gif',
        'https://cdn.weeb.sh/images/SyQ0_OmvZ.gif',
        'https://cdn.weeb.sh/images/BJ0Uovd_Z.gif',
        'https://cdn.weeb.sh/images/r1v2_uQvb.gif',
        'https://cdn.weeb.sh/images/BJcMf_7PZ.gif',
        'https://cdn.weeb.sh/images/BJdSVur_Z.gif',
        'https://cdn.weeb.sh/images/BkZ-X1Yv-.gif',
        'https://cdn.weeb.sh/images/rJnK2ItdZ.gif',
        'https://cdn.weeb.sh/images/HkfgF_QvW.gif',
        'https://cdn.weeb.sh/images/ByPGHkzDZ.gif',
        'https://cdn.weeb.sh/images/ryMUdOXvZ.gif',
        'https://cdn.weeb.sh/images/BJkOw1tDZ.gif',
        'https://cdn.weeb.sh/images/Hk3ehkFP-.gif',
        'https://cdn.weeb.sh/images/rJ_slR5eG.gif',
        'https://cdn.weeb.sh/images/SJfEmlmvb.gif',
        'https://cdn.weeb.sh/images/HywvU1KPZ.gif',
        'https://cdn.weeb.sh/images/ByP2hJKwW.gif'
    ],
    lick: [
        'https://cdn.weeb.sh/images/H1cR3kXvZ.gif',
        'https://cdn.weeb.sh/images/ry00h1YvW.gif',
        'https://cdn.weeb.sh/images/HkutO1tvZ.gif',
        'https://cdn.weeb.sh/images/BJmeh1tPZ.gif',
        'https://cdn.weeb.sh/images/S1o6Qeqtz.gif',
        'https://cdn.weeb.sh/images/HJfQKxKPb.gif',
        'https://cdn.weeb.sh/images/B1Gqe1tPZ.gif',
        'https://cdn.weeb.sh/images/BJRRyCYPb.gif',
        'https://cdn.weeb.sh/images/rk8glkyDb.gif',
        'https://cdn.weeb.sh/images/H1cR3kXvZ.gif',
        'https://cdn.weeb.sh/images/ry00h1YvW.gif',
        'https://cdn.weeb.sh/images/HkutO1tvZ.gif',
        'https://cdn.weeb.sh/images/BJmeh1tPZ.gif',
        'https://cdn.weeb.sh/images/S1o6Qeqtz.gif',
        'https://cdn.weeb.sh/images/HJfQKxKPb.gif',
        'https://cdn.weeb.sh/images/B1Gqe1tPZ.gif',
        'https://cdn.weeb.sh/images/BJRRyCYPb.gif',
        'https://cdn.weeb.sh/images/rk8glkyDb.gif',
        'https://cdn.weeb.sh/images/H1cR3kXvZ.gif',
        'https://cdn.weeb.sh/images/ry00h1YvW.gif',
        'https://cdn.weeb.sh/images/HkutO1tvZ.gif',
        'https://cdn.weeb.sh/images/BJmeh1tPZ.gif',
        'https://cdn.weeb.sh/images/S1o6Qeqtz.gif',
        'https://cdn.weeb.sh/images/HJfQKxKPb.gif',
        'https://cdn.weeb.sh/images/B1Gqe1tPZ.gif'
    ],
    yeet: [
        'https://cdn.weeb.sh/images/B1rpAWQT-.gif',
        'https://cdn.weeb.sh/images/BJg7eTVbG.gif',
        'https://cdn.weeb.sh/images/HyPLIvk0Z.gif',
        'https://cdn.weeb.sh/images/HkskD56hG.gif',
        'https://cdn.weeb.sh/images/Bkjv2a_PZ.gif',
        'https://cdn.weeb.sh/images/HkpjhOLRP.gif',
        'https://cdn.weeb.sh/images/BJgsWDQvZ.gif',
        'https://cdn.weeb.sh/images/SkZTXY1wW.gif',
        'https://cdn.weeb.sh/images/SJdB0OQvW.gif',
        'https://cdn.weeb.sh/images/HkJ6-eXvZ.gif',
        'https://cdn.weeb.sh/images/rJnVC6btZ.gif',
        'https://cdn.weeb.sh/images/SkdmoO_vW.gif',
        'https://cdn.weeb.sh/images/rykRLmFvb.gif',
        'https://cdn.weeb.sh/images/SkYTCKV0W.gif',
        'https://cdn.weeb.sh/images/B1rpAWQT-.gif',
        'https://cdn.weeb.sh/images/BJg7eTVbG.gif',
        'https://cdn.weeb.sh/images/HyPLIvk0Z.gif',
        'https://cdn.weeb.sh/images/HkskD56hG.gif',
        'https://cdn.weeb.sh/images/Bkjv2a_PZ.gif',
        'https://cdn.weeb.sh/images/HkpjhOLRP.gif',
        'https://cdn.weeb.sh/images/BJgsWDQvZ.gif',
        'https://cdn.weeb.sh/images/SkZTXY1wW.gif',
        'https://cdn.weeb.sh/images/SJdB0OQvW.gif',
        'https://cdn.weeb.sh/images/HkJ6-eXvZ.gif',
        'https://cdn.weeb.sh/images/rJnVC6btZ.gif'
    ],
    kill: [
        'https://cdn.weeb.sh/images/B1rpAWQT-.gif',
        'https://cdn.weeb.sh/images/BJg7eTVbG.gif',
        'https://cdn.weeb.sh/images/HyPLIvk0Z.gif',
        'https://cdn.weeb.sh/images/HkskD56hG.gif',
        'https://cdn.weeb.sh/images/Bkjv2a_PZ.gif',
        'https://cdn.weeb.sh/images/HkpjhOLRP.gif',
        'https://cdn.weeb.sh/images/BJgsWDQvZ.gif',
        'https://cdn.weeb.sh/images/SkZTXY1wW.gif',
        'https://cdn.weeb.sh/images/SJdB0OQvW.gif',
        'https://cdn.weeb.sh/images/HkJ6-eXvZ.gif',
        'https://cdn.weeb.sh/images/rJnVC6btZ.gif',
        'https://cdn.weeb.sh/images/SkdmoO_vW.gif',
        'https://cdn.weeb.sh/images/rykRLmFvb.gif',
        'https://cdn.weeb.sh/images/SkYTCKV0W.gif',
        'https://cdn.weeb.sh/images/B1rpAWQT-.gif',
        'https://cdn.weeb.sh/images/BJg7eTVbG.gif',
        'https://cdn.weeb.sh/images/HyPLIvk0Z.gif',
        'https://cdn.weeb.sh/images/HkskD56hG.gif',
        'https://cdn.weeb.sh/images/Bkjv2a_PZ.gif',
        'https://cdn.weeb.sh/images/HkpjhOLRP.gif',
        'https://cdn.weeb.sh/images/BJgsWDQvZ.gif',
        'https://cdn.weeb.sh/images/SkZTXY1wW.gif',
        'https://cdn.weeb.sh/images/SJdB0OQvW.gif',
        'https://cdn.weeb.sh/images/HkJ6-eXvZ.gif',
        'https://cdn.weeb.sh/images/rJnVC6btZ.gif'
    ]
};

// aliases PT → chave LOCAL
const ALIAS = {
    abraco: 'hug',
    beijo: 'kiss',
    tapa: 'slap',
    carinho: 'pat',
    cutucar: 'poke',
    morder: 'bite',
    chorar: 'cry',
    dancar: 'dance',
    cafune: 'cuddle',
    acenar: 'wave',
    corar: 'blush',
    sorrir: 'smile',
    rir: 'happy',
    maos: 'handhold',
    lambida: 'lick',
    matar: 'kill',
    piscadela: 'wink',
    highfive: 'highfive',
    bonk: 'bonk'
};

function resolveKey(category) {
    const k = String(category || '').toLowerCase();
    return ALIAS[k] || k;
}

function pickLocal(category) {
    const key = resolveKey(category);
    const list = LOCAL[key] || LOCAL.hug;
    if (!list?.length) return null;
    return list[Math.floor(Math.random() * list.length)];
}

async function fetchWaifu(category) {
    const ep = WAIFU[category] || WAIFU[resolveKey(category)];
    if (!ep) return null;
    try {
        const res = await fetch(`https://api.waifu.pics/sfw/${ep}`, {
            headers: { Accept: 'application/json' }
        });
        if (!res.ok) return null;
        const data = await res.json();
        return data?.url || null;
    } catch {
        return null;
    }
}

async function fetchNekos(category) {
    const ep = NEKOS[category] || NEKOS[resolveKey(category)];
    if (!ep) return null;
    try {
        const res = await fetch(`https://nekos.best/api/v2/${ep}`, {
            headers: { Accept: 'application/json' }
        });
        if (!res.ok) return null;
        const data = await res.json();
        return data?.results?.[0]?.url || null;
    } catch {
        return null;
    }
}

/** Escolhe GIF: APIs online primeiro, depois local (sempre ≥ 1) */
async function pickAsync(category) {
    const online = (await fetchWaifu(category)) || (await fetchNekos(category));
    if (online) return online;
    return pickLocal(category);
}

function pick(category) {
    return pickLocal(category);
}

function count(category) {
    const key = resolveKey(category);
    return (LOCAL[key] || []).length;
}

module.exports = {
    LOCAL,
    MAP: LOCAL,
    pick,
    pickAsync,
    count,
    fetchWaifu,
    fetchNekos
};
